// Fonts
import { font_sans } from "./fonts";
// Css
import "./globals.css";
// Meta Tags
export const metadata = {
  title: "Quentis",
  description: "Generated by Quentis",
};
// Components
import Header from "@/components/Header/Header";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font_sans.variable} antialiased font-sans font-normal text-[16px] leading-normal`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
